export const ADD_CONSTRUCTOR_INGREDIENT = 'ADD_CONSTRUCTOR_INGREDIENT'; 
export const ADD_CONSTRUCTOR_BUN = 'ADD_CONSTRUCTOR_BUN'; 
export const REMOVE_CONSTRUCTOR_INGREDIENT = 'REMOVE_CONSTRUCTOR_INGREDIENT'; 
export const UPDATE_CONSTRUCTOR_LIST = 'UPDATE_CONSTRUCTOR_LIST'; 
export const CLEAR_CONSTRUCTOR = 'CLEAR_CONSTRUCTOR'; 